application:
  name: "ethereal-groves"
  project: "ethereal-groves"
  organization: "QoveryCommunity"
  # publicly_accessible: true
routers:
- name: "main-ethereal-groves"
  custom_domains:
    - branch: "main"
      domain: "light.emdm.io"
  routes:
  - application_name: "ethereal-groves"
    paths:
    - "/*"

